# Generated by Django 3.1.2 on 2020-10-27 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20201027_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listtask',
            name='user',
        ),
    ]
