# Generated by Django 3.1.2 on 2020-10-27 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_listtask_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listtask',
            name='tasks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.task'),
        ),
    ]
