# Generated by Django 3.1.2 on 2020-10-28 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20201027_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listtask',
            name='tasks',
        ),
        migrations.AlterField(
            model_name='task',
            name='list_tasks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.listtask'),
        ),
    ]
