# Generated by Django 3.1.2 on 2020-10-28 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20201028_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='list_tasks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.listtask'),
        ),
    ]
